name: build-windows-2019-cpu

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Prepare vcpkg
      uses: lukka/run-vcpkg@v3
      with:
        vcpkgArguments: openssl
        vcpkgGitCommitId: 6185aa76504a5025f36754324abf307cc776f3da
        vcpkgDirectory: ${{ github.workspace }}/vcpkg/
        vcpkgTriplet: x64-windows

    - name: Run CMake
      uses: lukka/run-cmake@v2
      with:
        buildDirectory: ${{ github.workspace }}/build/
        cmakeAppendedArgs: -G Ninja
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: ${{ github.workspace }}/CMakeSettings.json
        useVcpkgToolchainFile: true

